### ISSUE TITLE
show more results in video or gif format

### ISSUE THREAD

**Issue by miibotree** [JohannesVerherstraeten/semantic-video-segmentation#1]
wonderful work!!! could you please update the readme file with more results in video or gif format to show the enhancing temporal consistency more clearly?

**Comment by JohannesVerherstraeten** [comment]
Thanks! I added the examples folder, with some generated sequence segmentations. Note that the consistency improves over time, as the first frames are used to initialize the recurrent network state. The long sequences are therefore the most representative I'd say.
